// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TenderDocs.Infrastructure.Persistence;

#nullable disable

namespace TenderDocs.Infrastructure.Persistence.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("20260101000000_InitialCreate")]
partial class InitialCreate
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("TenderDocs.Domain.Entities.Organization", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uuid");
                b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<Guid?>("CreatedById").HasColumnType("uuid");
                b.Property<DateTimeOffset?>("DeletedAt").HasColumnType("timestamp with time zone");
                b.Property<bool>("DemoMode").HasColumnType("boolean");
                b.Property<bool>("IsDeleted").HasColumnType("boolean");
                b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
                b.Property<string>("Slug").IsRequired().HasColumnType("text");
                b.Property<DateTimeOffset?>("UpdatedAt").HasColumnType("timestamp with time zone");
                b.Property<Guid?>("UpdatedById").HasColumnType("uuid");
                b.HasKey("Id");
                b.HasIndex("Slug").IsUnique();
                b.ToTable("organizations");
            });

            modelBuilder.Entity("TenderDocs.Domain.Entities.User", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uuid");
                b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<Guid?>("CreatedById").HasColumnType("uuid");
                b.Property<DateTimeOffset?>("DeletedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("Email").IsRequired().HasMaxLength(256).HasColumnType("character varying(256)");
                b.Property<string>("FullName").IsRequired().HasMaxLength(120).HasColumnType("character varying(120)");
                b.Property<string>("GoogleId").HasColumnType("text");
                b.Property<string>("Initials").IsRequired().HasMaxLength(4).HasColumnType("character varying(4)");
                b.Property<bool>("IsActive").HasColumnType("boolean");
                b.Property<bool>("IsDeleted").HasColumnType("boolean");
                b.Property<DateTimeOffset?>("LastLoginAt").HasColumnType("timestamp with time zone");
                b.Property<Guid>("OrganizationId").HasColumnType("uuid");
                b.Property<string>("PasswordHash").HasColumnType("text");
                b.Property<int>("Role").HasColumnType("integer");
                b.Property<DateTimeOffset?>("UpdatedAt").HasColumnType("timestamp with time zone");
                b.Property<Guid?>("UpdatedById").HasColumnType("uuid");
                b.HasKey("Id");
                b.HasIndex("Email").IsUnique();
                b.HasIndex("GoogleId");
                b.HasIndex("OrganizationId");
                b.ToTable("users");
            });

            modelBuilder.Entity("TenderDocs.Domain.Entities.RefreshToken", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uuid");
                b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("CreatedByIp").HasColumnType("text");
                b.Property<DateTimeOffset>("ExpiresAt").HasColumnType("timestamp with time zone");
                b.Property<string>("ReplacedByToken").HasColumnType("text");
                b.Property<DateTimeOffset?>("RevokedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("Token").IsRequired().HasMaxLength(256).HasColumnType("character varying(256)");
                b.Property<Guid>("UserId").HasColumnType("uuid");
                b.HasKey("Id");
                b.HasIndex("Token").IsUnique();
                b.HasIndex("UserId");
                b.ToTable("refresh_tokens");
            });

            modelBuilder.Entity("TenderDocs.Domain.Entities.Folder", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uuid");
                b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<Guid?>("CreatedById").HasColumnType("uuid");
                b.Property<DateTimeOffset?>("DeletedAt").HasColumnType("timestamp with time zone");
                b.Property<int>("Depth").HasColumnType("integer");
                b.Property<bool>("IsDeleted").HasColumnType("boolean");
                b.Property<string>("MaterializedPath").IsRequired().HasMaxLength(2048).HasColumnType("character varying(2048)");
                b.Property<string>("Name").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
                b.Property<Guid>("OrganizationId").HasColumnType("uuid");
                b.Property<Guid?>("ParentFolderId").HasColumnType("uuid");
                b.Property<Guid?>("ProjectId").HasColumnType("uuid");
                b.Property<DateTimeOffset?>("UpdatedAt").HasColumnType("timestamp with time zone");
                b.Property<Guid?>("UpdatedById").HasColumnType("uuid");
                b.HasKey("Id");
                b.HasIndex("MaterializedPath");
                b.HasIndex("ParentFolderId");
                b.HasIndex("ProjectId");
                b.HasIndex("OrganizationId", "ParentFolderId");
                b.ToTable("folders");
            });

            modelBuilder.Entity("TenderDocs.Domain.Entities.Project", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uuid");
                b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<Guid?>("CreatedById").HasColumnType("uuid");
                b.Property<DateTimeOffset?>("DeletedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("Description").HasColumnType("text");
                b.Property<bool>("IsDeleted").HasColumnType("boolean");
                b.Property<string>("Name").IsRequired().HasMaxLength(150).HasColumnType("character varying(150)");
                b.Property<Guid>("OrganizationId").HasColumnType("uuid");
                b.Property<Guid?>("RootFolderId").HasColumnType("uuid");
                b.Property<DateTimeOffset?>("UpdatedAt").HasColumnType("timestamp with time zone");
                b.Property<Guid?>("UpdatedById").HasColumnType("uuid");
                b.HasKey("Id");
                b.HasIndex("RootFolderId");
                b.HasIndex("OrganizationId", "Name");
                b.ToTable("projects");
            });

            modelBuilder.Entity("TenderDocs.Domain.Entities.Document", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uuid");
                b.Property<string>("Checksum").HasColumnType("text");
                b.Property<string>("ContentType").IsRequired().HasMaxLength(150).HasColumnType("character varying(150)");
                b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<Guid?>("CreatedById").HasColumnType("uuid");
                b.Property<DateTimeOffset?>("DeletedAt").HasColumnType("timestamp with time zone");
                b.Property<int>("DocumentType").HasColumnType("integer");
                b.Property<DateOnly?>("ExpiryDate").HasColumnType("date");
                b.Property<long>("FileSizeBytes").HasColumnType("bigint");
                b.Property<string>("FinancialYear").HasMaxLength(20).HasColumnType("character varying(20)");
                b.Property<Guid?>("FolderId").HasColumnType("uuid");
                b.Property<bool>("IsDeleted").HasColumnType("boolean");
                b.Property<DateOnly?>("IssueDate").HasColumnType("date");
                b.Property<string>("IssuingAuthority").HasMaxLength(200).HasColumnType("character varying(200)");
                b.Property<string>("Name").IsRequired().HasMaxLength(260).HasColumnType("character varying(260)");
                b.Property<string>("Notes").HasColumnType("text");
                b.Property<Guid>("OrganizationId").HasColumnType("uuid");
                b.Property<int>("StorageProvider").HasColumnType("integer");
                b.Property<string>("StorageKey").IsRequired().HasMaxLength(1024).HasColumnType("character varying(1024)");
                b.Property<DateTimeOffset?>("UpdatedAt").HasColumnType("timestamp with time zone");
                b.Property<Guid?>("UpdatedById").HasColumnType("uuid");
                b.Property<Guid?>("UploadedById").HasColumnType("uuid");
                b.HasKey("Id");
                b.HasIndex("FolderId");
                b.HasIndex("UploadedById");
                b.HasIndex("OrganizationId", "DocumentType");
                b.HasIndex("OrganizationId", "ExpiryDate");
                b.ToTable("documents");
            });

            modelBuilder.Entity("TenderDocs.Domain.Entities.DocumentVersion", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uuid");
                b.Property<string>("Checksum").HasColumnType("text");
                b.Property<string>("ContentType").IsRequired().HasColumnType("text");
                b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<Guid>("DocumentId").HasColumnType("uuid");
                b.Property<long>("FileSizeBytes").HasColumnType("bigint");
                b.Property<int>("StorageProvider").HasColumnType("integer");
                b.Property<string>("StorageKey").IsRequired().HasMaxLength(1024).HasColumnType("character varying(1024)");
                b.Property<Guid?>("UploadedById").HasColumnType("uuid");
                b.Property<int>("VersionNumber").HasColumnType("integer");
                b.HasKey("Id");
                b.HasIndex("DocumentId", "VersionNumber").IsUnique();
                b.ToTable("document_versions");
            });

            modelBuilder.Entity("TenderDocs.Domain.Entities.ProjectRequirement", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uuid");
                b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<Guid?>("CreatedById").HasColumnType("uuid");
                b.Property<DateTimeOffset?>("DeletedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("Description").HasColumnType("text");
                b.Property<bool>("IsDeleted").HasColumnType("boolean");
                b.Property<bool>("IsMandatory").HasColumnType("boolean");
                b.Property<string>("Name").IsRequired().HasMaxLength(150).HasColumnType("character varying(150)");
                b.Property<Guid>("ProjectId").HasColumnType("uuid");
                b.Property<int>("SortOrder").HasColumnType("integer");
                b.Property<DateTimeOffset?>("UpdatedAt").HasColumnType("timestamp with time zone");
                b.Property<Guid?>("UpdatedById").HasColumnType("uuid");
                b.HasKey("Id");
                b.HasIndex("ProjectId");
                b.ToTable("project_requirements");
            });

            modelBuilder.Entity("TenderDocs.Domain.Entities.ProjectDocumentAssignment", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uuid");
                b.Property<Guid?>("AssignedById").HasColumnType("uuid");
                b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<Guid?>("CreatedById").HasColumnType("uuid");
                b.Property<DateTimeOffset?>("DeletedAt").HasColumnType("timestamp with time zone");
                b.Property<Guid>("DocumentId").HasColumnType("uuid");
                b.Property<bool>("IsDeleted").HasColumnType("boolean");
                b.Property<Guid>("ProjectId").HasColumnType("uuid");
                b.Property<Guid?>("RequirementId").HasColumnType("uuid");
                b.Property<DateTimeOffset?>("UpdatedAt").HasColumnType("timestamp with time zone");
                b.Property<Guid?>("UpdatedById").HasColumnType("uuid");
                b.HasKey("Id");
                b.HasIndex("DocumentId");
                b.HasIndex("RequirementId");
                b.HasIndex("ProjectId", "DocumentId").IsUnique();
                b.ToTable("project_document_assignments");
            });

            modelBuilder.Entity("TenderDocs.Domain.Entities.Tag", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uuid");
                b.Property<string>("Color").HasColumnType("text");
                b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<Guid?>("CreatedById").HasColumnType("uuid");
                b.Property<DateTimeOffset?>("DeletedAt").HasColumnType("timestamp with time zone");
                b.Property<bool>("IsDeleted").HasColumnType("boolean");
                b.Property<string>("Name").IsRequired().HasMaxLength(60).HasColumnType("character varying(60)");
                b.Property<Guid>("OrganizationId").HasColumnType("uuid");
                b.Property<DateTimeOffset?>("UpdatedAt").HasColumnType("timestamp with time zone");
                b.Property<Guid?>("UpdatedById").HasColumnType("uuid");
                b.HasKey("Id");
                b.HasIndex("OrganizationId", "Name").IsUnique();
                b.ToTable("tags");
            });

            modelBuilder.Entity("TenderDocs.Domain.Entities.DocumentTag", b =>
            {
                b.Property<Guid>("DocumentId").HasColumnType("uuid");
                b.Property<Guid>("TagId").HasColumnType("uuid");
                b.HasKey("DocumentId", "TagId");
                b.HasIndex("TagId");
                b.ToTable("document_tags");
            });

            modelBuilder.Entity("TenderDocs.Domain.Entities.Notification", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uuid");
                b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<bool>("IsRead").HasColumnType("boolean");
                b.Property<string>("Message").IsRequired().HasColumnType("text");
                b.Property<Guid>("OrganizationId").HasColumnType("uuid");
                b.Property<Guid?>("RelatedEntityId").HasColumnType("uuid");
                b.Property<string>("RelatedEntityType").HasColumnType("text");
                b.Property<string>("Title").IsRequired().HasMaxLength(200).HasColumnType("character varying(200)");
                b.Property<int>("Type").HasColumnType("integer");
                b.Property<Guid>("UserId").HasColumnType("uuid");
                b.HasKey("Id");
                b.HasIndex("UserId", "IsRead");
                b.ToTable("notifications");
            });

            modelBuilder.Entity("TenderDocs.Domain.Entities.AuditLog", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uuid");
                b.Property<int>("Action").HasColumnType("integer");
                b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("DetailsJson").HasColumnType("jsonb");
                b.Property<Guid?>("EntityId").HasColumnType("uuid");
                b.Property<string>("EntityType").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                b.Property<string>("IpAddress").HasColumnType("text");
                b.Property<Guid>("OrganizationId").HasColumnType("uuid");
                b.Property<Guid?>("UserId").HasColumnType("uuid");
                b.HasKey("Id");
                b.HasIndex("OrganizationId", "CreatedAt");
                b.ToTable("audit_logs");
            });

            modelBuilder.Entity("TenderDocs.Domain.Entities.StorageConnection", b =>
            {
                b.Property<Guid>("Id").HasColumnType("uuid");
                b.Property<string>("CredentialsEncrypted").HasColumnType("text");
                b.Property<DateTimeOffset>("CreatedAt").HasColumnType("timestamp with time zone");
                b.Property<Guid?>("CreatedById").HasColumnType("uuid");
                b.Property<DateTimeOffset?>("DeletedAt").HasColumnType("timestamp with time zone");
                b.Property<string>("DisplayName").IsRequired().HasMaxLength(100).HasColumnType("character varying(100)");
                b.Property<bool>("IsActive").HasColumnType("boolean");
                b.Property<bool>("IsDeleted").HasColumnType("boolean");
                b.Property<Guid>("OrganizationId").HasColumnType("uuid");
                b.Property<int>("ProviderType").HasColumnType("integer");
                b.Property<DateTimeOffset?>("UpdatedAt").HasColumnType("timestamp with time zone");
                b.Property<Guid?>("UpdatedById").HasColumnType("uuid");
                b.HasKey("Id");
                b.HasIndex("OrganizationId", "IsActive");
                b.ToTable("storage_connections");
            });

            modelBuilder.Entity("TenderDocs.Domain.Entities.User", b =>
            {
                b.HasOne("TenderDocs.Domain.Entities.Organization", "Organization")
                    .WithMany("Users").HasForeignKey("OrganizationId")
                    .OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.Navigation("Organization");
            });

            modelBuilder.Entity("TenderDocs.Domain.Entities.RefreshToken", b =>
            {
                b.HasOne("TenderDocs.Domain.Entities.User", "User")
                    .WithMany("RefreshTokens").HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.Navigation("User");
            });

            modelBuilder.Entity("TenderDocs.Domain.Entities.Folder", b =>
            {
                b.HasOne("TenderDocs.Domain.Entities.Organization", "Organization")
                    .WithMany().HasForeignKey("OrganizationId")
                    .OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.HasOne("TenderDocs.Domain.Entities.Folder", "ParentFolder")
                    .WithMany("Children").HasForeignKey("ParentFolderId")
                    .OnDelete(DeleteBehavior.Restrict);
                b.HasOne("TenderDocs.Domain.Entities.Project", "Project")
                    .WithMany().HasForeignKey("ProjectId")
                    .OnDelete(DeleteBehavior.SetNull);
                b.Navigation("Organization");
                b.Navigation("ParentFolder");
                b.Navigation("Project");
            });

            modelBuilder.Entity("TenderDocs.Domain.Entities.Project", b =>
            {
                b.HasOne("TenderDocs.Domain.Entities.Organization", "Organization")
                    .WithMany("Projects").HasForeignKey("OrganizationId")
                    .OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.HasOne("TenderDocs.Domain.Entities.Folder", "RootFolder")
                    .WithMany().HasForeignKey("RootFolderId")
                    .OnDelete(DeleteBehavior.SetNull);
                b.Navigation("Organization");
                b.Navigation("RootFolder");
            });

            modelBuilder.Entity("TenderDocs.Domain.Entities.Document", b =>
            {
                b.HasOne("TenderDocs.Domain.Entities.Organization", null)
                    .WithMany("Documents").HasForeignKey("OrganizationId")
                    .OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.HasOne("TenderDocs.Domain.Entities.Folder", "Folder")
                    .WithMany("Documents").HasForeignKey("FolderId")
                    .OnDelete(DeleteBehavior.SetNull);
                b.HasOne("TenderDocs.Domain.Entities.User", "UploadedBy")
                    .WithMany().HasForeignKey("UploadedById")
                    .OnDelete(DeleteBehavior.SetNull);
                b.Navigation("Folder");
                b.Navigation("UploadedBy");
            });

            modelBuilder.Entity("TenderDocs.Domain.Entities.DocumentVersion", b =>
            {
                b.HasOne("TenderDocs.Domain.Entities.Document", "Document")
                    .WithMany("Versions").HasForeignKey("DocumentId")
                    .OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.Navigation("Document");
            });

            modelBuilder.Entity("TenderDocs.Domain.Entities.ProjectRequirement", b =>
            {
                b.HasOne("TenderDocs.Domain.Entities.Project", "Project")
                    .WithMany("Requirements").HasForeignKey("ProjectId")
                    .OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.Navigation("Project");
            });

            modelBuilder.Entity("TenderDocs.Domain.Entities.ProjectDocumentAssignment", b =>
            {
                b.HasOne("TenderDocs.Domain.Entities.Document", "Document")
                    .WithMany("Assignments").HasForeignKey("DocumentId")
                    .OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.HasOne("TenderDocs.Domain.Entities.Project", "Project")
                    .WithMany("Assignments").HasForeignKey("ProjectId")
                    .OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.HasOne("TenderDocs.Domain.Entities.ProjectRequirement", "Requirement")
                    .WithMany("Assignments").HasForeignKey("RequirementId")
                    .OnDelete(DeleteBehavior.SetNull);
                b.Navigation("Document");
                b.Navigation("Project");
                b.Navigation("Requirement");
            });

            modelBuilder.Entity("TenderDocs.Domain.Entities.DocumentTag", b =>
            {
                b.HasOne("TenderDocs.Domain.Entities.Document", "Document")
                    .WithMany("DocumentTags").HasForeignKey("DocumentId")
                    .OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.HasOne("TenderDocs.Domain.Entities.Tag", "Tag")
                    .WithMany("DocumentTags").HasForeignKey("TagId")
                    .OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.Navigation("Document");
                b.Navigation("Tag");
            });

            modelBuilder.Entity("TenderDocs.Domain.Entities.Organization", b =>
            {
                b.Navigation("Documents");
                b.Navigation("Projects");
                b.Navigation("Users");
            });

            modelBuilder.Entity("TenderDocs.Domain.Entities.Folder", b =>
            {
                b.Navigation("Children");
                b.Navigation("Documents");
            });

            modelBuilder.Entity("TenderDocs.Domain.Entities.Project", b =>
            {
                b.Navigation("Assignments");
                b.Navigation("Requirements");
            });

            modelBuilder.Entity("TenderDocs.Domain.Entities.Document", b =>
            {
                b.Navigation("Assignments");
                b.Navigation("DocumentTags");
                b.Navigation("Versions");
            });

            modelBuilder.Entity("TenderDocs.Domain.Entities.ProjectRequirement", b =>
            {
                b.Navigation("Assignments");
            });

            modelBuilder.Entity("TenderDocs.Domain.Entities.Tag", b =>
            {
                b.Navigation("DocumentTags");
            });

            modelBuilder.Entity("TenderDocs.Domain.Entities.User", b =>
            {
                b.Navigation("RefreshTokens");
            });
#pragma warning restore 612, 618
    }
}
